### PR TITLE
Tests are passing...

### PR DESCRIPTION
**Pull request by zenangst**
... on my machine.

### CODE REVIEW

**Comment by onmyway133** [comment]
then we trust Vadym instead of Travis 😄

**Comment by zenangst** [comment]
❤️ @vadymmarkov

**Review by fespinoza — APPROVED** [review]

**Comment by vadymmarkov** [comment]
😄

**Comment by sindrenm** [comment]
:laughing:

**Comment by sindrenm** [comment]
:rofl:

**Pull request merged**
