### PR TITLE
Quote Felipe on his bug creation

### PR DESCRIPTION
**Pull request by sindrenm**
“Sometimes, I do create bugs!” —Felipe

### CODE REVIEW

**Comment by sindrenm** [comment]
Poop. Forgot a comma. Seems like I also sometimes create bugs.

**Comment by sindrenm** [comment]
There we go!

**Comment by zenangst** [comment]
I approve of this!

**Comment by sindrenm** [comment]
What, @fespinoza writing bugs? :smile:

**Comment by zenangst** [comment]
That his statement is truthy 🤓

**Comment by sindrenm** [comment]
Ahh!

**Pull request merged**
