### PR TITLE
Update quotes.js

### PR DESCRIPTION
**Pull request by thuyranosaurus**

### CODE REVIEW

**Comment by timkurvers** [comment]
image

**Comment by sindrenm** [comment]
Hahahahaha!

**Comment by sindrenm** [comment]
I'm impressed, @RamonGilabert! :eggplant:

**Comment by gauravtiwari** [comment]
Supert @thuygianguyen

**Comment by RamonGilabert** [comment]
I don't really know if I quite know the meaning of stiff. I used Google Translate to put it in the sentence...

**Comment by zenangst** [comment]
rick-and-morty- -rick-sanchez-r m- -2440434

**Comment by RamonGilabert** [comment]
@zenangst. LITTLE RICK! :metal:

**Pull request merged**
