### PR TITLE
Add JS function to prevent text selection on body

### PR DESCRIPTION
**Pull request by zenangst**
I found it annoying that text sometimes got selected when clicking in the quote, this PR should fix that by adding some attributes to the body element.

### CODE REVIEW

**Comment by jgorset** [comment]
@sindrenm gonna be very mad at this.

**Comment by zenangst** [comment]
Oh, it seems that this was already discussed and shot down by previous discussions and PR's.
I'm just gonna close this and go sit in a corner somewhere.

a40488715f019f9078d7cd1abc348fbe

**Comment by jgorset** [comment]
Here's some :cake: anyway!

**Comment by sindrenm** [comment]
Haha!

**Comment by sindrenm** [comment]
Like, why would you want to prevent text selection? :stuck_out_tongue:

**Comment by zenangst** [comment]
Because when you tap it, it changes!

**Comment by sindrenm** [comment]
It doesn't in the latest version (fixed in #4), but that's not deployed, it seems. :smile:

**Comment by zenangst** [comment]
Oh, then don't mind me.

tumblr_inline_milqgk6lqz1qz4rgp

**Comment by sindrenm** [comment]
:grinning:

**Comment by RamonGilabert** [comment]
:smile:

**Pull request closed without merging**
