### PR TITLE
Update quotes.js

### PR DESCRIPTION
**Pull request by thuyranosaurus**

### CODE REVIEW

**Comment by jgorset** [comment]
So that's what you were all in tears about! 😄

**Comment by toothfairy** [comment]
@thuygianguyen there is comma missed after 

```
{
    quote: "I don't hate MongoDB",
    author: "Francesco"
  }
```

**Comment by RamonGilabert** [comment]
I added it myself after merging, @toothfairy!

**Comment by toothfairy** [comment]
good boy @RamonGilabert

**Comment by RamonGilabert** [comment]
MERGING WITH MASTER!

**Pull request merged**
