### PR TITLE
Developers who kind of develop

### PR DESCRIPTION
**Pull request by fespinoza**
@gilstad quote

### CODE REVIEW

**Comment by jgorset** [comment]
<3 @gilstad

**Comment by gilstad** [comment]
I remember it as: "Developers know more or less how to develop stuff" ;)

**Comment by fespinoza** [comment]
what do you say @onmyway133 @changxiangzhong @zenangst do we change it?

**Comment by zenangst** [comment]
I guess we have to go with the quote creator on this.

**Comment by sindrenm** [comment]
#35

**Pull request merged**
