### PR TITLE
complaint

### PR DESCRIPTION
**Pull request by SteveBenner**
@sindrenm totally OKAY'd this, I think :grinning:

### CODE REVIEW

**Comment by fespinoza** [comment]
not sure if we should publish this... as anyone can access the website hypersays.com

**Comment by jgorset** [comment]
Yeah, that would probably not be a good thing to say. Officially. :wink:

**Comment by SteveBenner** [comment]
Oh, my bad on this :open_mouth: . I had actually thought it would not be public, based on what sindre said. Delete it! The guys at UDI are after all just doing their jobs, I was just frustrated at the time :)

**Comment by sindrenm** [comment]
Like the rename, though. xP

**Pull request closed without merging**
