### PR TITLE
"I don’t remember exactly every line of code and logic in the whole project" – Felipe

### PR DESCRIPTION
**Pull request by jgorset**

### CODE REVIEW

**Comment by espenhogbakk** [comment]
If he doesn't, does he really deserve a job @hyper?

**Comment by zenangst** [comment]
@espenhogbakk: 🤔

**Comment by zenangst** [comment]
@espenhogbakk: 🤔💭

**Comment by fespinoza** [comment]
ok, i'll pack my things, i'll leave to chile :(

**Comment by espenhogbakk** [comment]
Ok, now i'm feeling like a

7477846239188242185 jpeg___1_500_1_500_cb94de6a_

**Comment by sindrenm** [comment]
image

**Pull request merged**
